build status survey
- nitrokey-3
bumping release added lots of @git cargo dependencies
manual hash pinning needs to be done, unsure of build state

- nitrokey-fido2, nitrokey-pro
> error: attribute 'version' missing
insruitable, comes from an assertion in systemd?

- nitrokey-start
> /nix/store/l1m81cnwwhhkl80zkizf1d3r7ab7hiwj-arm-none-eabi-binutils-2.42/bin/arm-none-eabi-ld: warning:
-z relro ignored
> /nix/store/l1m81cnwwhhkl80zkizf1d3r7ab7hiwj-arm-none-eabi-binutils-2.42/bin/arm-none-eabi-ld: build/gnu
k-no-vidpid.elf section `.gnuk_flash' will not fit in region `flash'
> /nix/store/l1m81cnwwhhkl80zkizf1d3r7ab7hiwj-arm-none-eabi-binutils-2.42/bin/arm-none-eabi-ld: region `f
lash' overflowed by 4112 bytes
> /nix/store/l1m81cnwwhhkl80zkizf1d3r7ab7hiwj-arm-none-eabi-binutils-2.42/bin/arm-none-eabi-ld: warning:
build/gnuk-no-vidpid.elf has a LOAD segment with RWX permissions
> collect2: error: ld returned 1 exit status
linker errors, hunch is this will be difficult to root-cause.

- nitrokey-storage, nitrokey-trng-rs232
work with version bump.

Signed-off-by: Jack Leightcap <jack@leightcap.com>